import sys
import os
import unittest
import pandas as pd
import numpy as np

# Add backend directory to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.forecasting.dataset import ForecastDataset
from app.forecasting.models.baseline import BaselineModel
from app.forecasting.evaluator import ModelEvaluator


class TestForecastingEnginePart1(unittest.TestCase):

    def setUp(self):
        # Create a mock dataset with 200 rows to ensure we have > 50 rows after indicators and shift(-30) dropna
        dates = pd.date_range(start="2026-01-01", periods=200)
        self.mock_df = pd.DataFrame({
            "date": dates,
            "open": np.random.uniform(150, 160, 200),
            "high": np.random.uniform(160, 170, 200),
            "low": np.random.uniform(140, 150, 200),
            "close": np.linspace(150, 180, 200) + np.random.normal(0, 1, 200),
            "volume": np.random.randint(1000, 5000, 200)
        })
        # Add technical indicators normally generated by pipeline
        from app.preprocessing.indicators import IndicatorBuilder
        self.mock_df = IndicatorBuilder().add_indicators(self.mock_df)

    def test_dataset_preparation(self):
        dataset = ForecastDataset(self.mock_df)
        
        # Verify target is 30-day close price
        first_row_date = dataset.df["date"].iloc[0]
        idx = self.mock_df[self.mock_df["date"] == first_row_date].index[0]
        close_t30 = float(self.mock_df["close"].iloc[idx + 30])
        
        self.assertAlmostEqual(dataset.df["target"].iloc[0], close_t30, places=4)
        self.assertTrue(len(dataset.df) > 0)

    def test_train_test_split(self):
        dataset = ForecastDataset(self.mock_df)
        X_train, X_test, y_train, y_test = dataset.split(test_size=0.2)
        
        self.assertEqual(len(X_train) + len(X_test), dataset.n_rows)

    def test_baseline_model(self):
        dataset = ForecastDataset(self.mock_df)
        X_train, X_test, y_train, y_test = dataset.split(test_size=0.2)
        
        model = BaselineModel()
        train_df = dataset.df.iloc[:len(X_train)]
        model.train(train_df)
        
        forecast = model.predict(horizon=30)
        
        self.assertEqual(len(forecast), 30)
        self.assertTrue(all(p > 0 for p in forecast))

    def test_sarimax_model(self):
        from app.forecasting.models.sarimax import SARIMAXModel
        dataset = ForecastDataset(self.mock_df)
        X_train, X_test, y_train, y_test = dataset.split(test_size=0.2)

        model = SARIMAXModel()
        train_df = dataset.df.iloc[:len(X_train)]
        model.train(train_df)

        forecast = model.predict(horizon=30)
        self.assertEqual(len(forecast), 30)
        self.assertTrue(hasattr(model, "last_confidence_intervals"))
        self.assertEqual(len(model.last_confidence_intervals), 30)
        for lower, upper in model.last_confidence_intervals:
            self.assertTrue(lower <= upper)

    def test_forecast_evaluator(self):
        y_true = np.array([150.0, 155.0, 160.0])
        y_pred = np.array([148.0, 156.0, 158.0])
        y_base = np.array([145.0, 150.0, 155.0])
        
        result = ModelEvaluator.compute("baseline", y_true, y_pred, y_base=y_base)
        
        self.assertAlmostEqual(result.rmse, np.sqrt((4.0 + 1.0 + 4.0) / 3.0), places=4)
        self.assertAlmostEqual(result.mae, 5.0 / 3.0, places=4)
        self.assertIsNotNone(result.direction_accuracy)
        self.assertIsNotNone(result.r2)

    def test_xgboost_model(self):
        from app.forecasting.models.xgboost import XGBoostModel
        dataset = ForecastDataset(self.mock_df)
        X_train, X_test, y_train, y_test = dataset.split(test_size=0.2)

        model = XGBoostModel()
        train_df = dataset.df.iloc[:len(X_train)]
        model.train(train_df)

        forecast = model.predict(horizon=30)
        self.assertEqual(len(forecast), 30)
        self.assertTrue(len(model.feature_importances_) > 0)

    def test_technical_adjustment_logic(self):
        from app.forecasting.models.baseline import BaselineModel
        model = BaselineModel()

        # Test positive (bullish) technical signal adjustment
        adj_positive = model.compute_technical_adjustment(
            predicted_price=150.0,
            last_close=100.0,
            technical_score=4.0,
            technical_confidence=80.0,
            bias_scale=0.4
        )
        # Expected: 4.0 * 0.4 * 0.8 = 1.28
        self.assertAlmostEqual(adj_positive, 1.28, places=4)

        # Test negative (bearish) technical signal adjustment
        adj_negative = model.compute_technical_adjustment(
            predicted_price=150.0,
            last_close=100.0,
            technical_score=-3.0,
            technical_confidence=90.0,
            bias_scale=0.4
        )
        # Expected: -3.0 * 0.4 * 0.9 = -1.08
        self.assertAlmostEqual(adj_negative, -1.08, places=4)

        # Test guardrail cap (2% max of today's close price = 2.0 LKR)
        adj_capped = model.compute_technical_adjustment(
            predicted_price=150.0,
            last_close=100.0,
            technical_score=10.0,
            technical_confidence=100.0,
            bias_scale=1.0
        )
        # Expected: Capped at 2.0
        self.assertAlmostEqual(adj_capped, 2.0, places=4)


if __name__ == "__main__":
    unittest.main()

